version: '3'
services:
  pythonapp:
    build: ./
    command: sh -c "sleep 20s ; python3 /app/app.py"
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  mysql:
    build: ./db_container/
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3333:3306"
