version: '3'
services:
  mysql-db:
    build: ./db_container/
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3333:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 5s
      retries: 3

  flaskapp:
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      mysql-db:
        condition: service_healthy
